// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCiILa38iBuv6JBzXvL1-VBBIp4ctdRSw',
    appId: '1:963496639241:web:19899cf0c733343fc1b1d8',
    messagingSenderId: '963496639241',
    projectId: 'flutterappfirebase-b8761',
    authDomain: 'flutterappfirebase-b8761.firebaseapp.com',
    storageBucket: 'flutterappfirebase-b8761.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE5jLaa3QYlj2GLBA-FKIV1tjM9pAc_uA',
    appId: '1:963496639241:android:5a0fb631c85e8b8fc1b1d8',
    messagingSenderId: '963496639241',
    projectId: 'flutterappfirebase-b8761',
    storageBucket: 'flutterappfirebase-b8761.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCifPQrJQmN9IVqk3ZZYwv7yXJYY1qZlvo',
    appId: '1:963496639241:ios:13e54d44a336325ac1b1d8',
    messagingSenderId: '963496639241',
    projectId: 'flutterappfirebase-b8761',
    storageBucket: 'flutterappfirebase-b8761.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCifPQrJQmN9IVqk3ZZYwv7yXJYY1qZlvo',
    appId: '1:963496639241:ios:13e54d44a336325ac1b1d8',
    messagingSenderId: '963496639241',
    projectId: 'flutterappfirebase-b8761',
    storageBucket: 'flutterappfirebase-b8761.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCiILa38iBuv6JBzXvL1-VBBIp4ctdRSw',
    appId: '1:963496639241:web:e17605a941313c57c1b1d8',
    messagingSenderId: '963496639241',
    projectId: 'flutterappfirebase-b8761',
    authDomain: 'flutterappfirebase-b8761.firebaseapp.com',
    storageBucket: 'flutterappfirebase-b8761.firebasestorage.app',
  );
}
